spec:
  template:
    spec:
      containers:
        - name: vertx
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: "/health"
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: "/health"
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 10
            successTreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi
          env:
            - name: JAVA_OPTIONS
              value: "-Dapplication.configmap=driver-service -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.SLF4JLogDelegateFactory"
          volumeMounts:
            - name: truststore
              mountPath: /app/truststore
      volumes:
        - secret:
            secretName: enmasse-truststore
          name: truststore