kafka.bootstrap.servers:
kafka.groupid: driver-service

kafka.topic.driver-command: topic-driver-command
kafka.topic.driver-event: topic-driver-event
kafka.topic.ride-event: topic-ride-event

http.port: 8080

# delay before sending a `DriverAssignedEvent` message
driver.assigned.min.delay: 1
driver.assigned.max.delay: 3
# delay before sending a `RideStartedEvent` message
ride.started.min.delay: 5
ride.started.max.delay: 10
# delay before sending a `RideEndedEvent` message
ride.ended.min.delay: 5
ride.ended.max.delay: 10
